#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfd58;
constexpr uint24_t FX_DATA_BYTES = 169750;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Levels
{
  constexpr uint24_t Puzzle_01 = 0x0187F8;
  constexpr uint24_t Puzzle_02 = 0x018813;
  constexpr uint24_t Puzzle_03 = 0x018837;
  constexpr uint24_t Puzzle_04 = 0x01884C;
  constexpr uint24_t Puzzle_05 = 0x018864;
  constexpr uint24_t Puzzle_06 = 0x018888;
  constexpr uint24_t Puzzle_07 = 0x0188AC;
  constexpr uint24_t Puzzle_08 = 0x0188CA;
  constexpr uint24_t Puzzle_09 = 0x0188F7;
  constexpr uint24_t Puzzle_10 = 0x01891E;
  constexpr uint24_t Puzzle_11 = 0x018945;
  constexpr uint24_t Puzzle_12 = 0x018960;
  constexpr uint24_t Puzzle_13 = 0x01897B;
  constexpr uint24_t Puzzle_14 = 0x0189A5;
  constexpr uint24_t Puzzle_15 = 0x0189CC;
  constexpr uint24_t Puzzle_16 = 0x0189F9;
  constexpr uint24_t Puzzle_17 = 0x018A1D;
  constexpr uint24_t Puzzle_18 = 0x018A44;
  constexpr uint24_t Puzzle_19 = 0x018A62;
  constexpr uint24_t Puzzle_20 = 0x018A7D;
  constexpr uint24_t Puzzle_21 = 0x018A9E;
  constexpr uint24_t Puzzle_22 = 0x018AB6;
  constexpr uint24_t Puzzle_23 = 0x018ADD;
  constexpr uint24_t Puzzle_24 = 0x018AFE;
  constexpr uint24_t Puzzle_25 = 0x018B1F;
  constexpr uint24_t Puzzle_26 = 0x018B49;
  constexpr uint24_t Puzzle_27 = 0x018B70;
  constexpr uint24_t Puzzle_28 = 0x018B91;
  constexpr uint24_t Puzzle_29 = 0x018BB8;
  constexpr uint24_t Puzzle_30 = 0x018BDF;
  constexpr uint24_t Puzzle_31 = 0x018C00;
  constexpr uint24_t Puzzle_32 = 0x018C24;
  constexpr uint24_t Puzzle_33 = 0x018C48;
  constexpr uint24_t Puzzle_34 = 0x018C6F;
  constexpr uint24_t Puzzle_35 = 0x018C96;
  constexpr uint24_t Puzzles = 0x018CBA;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x018D23;
  constexpr uint24_t FreeTheKey = 0x01A585;
  constexpr uint24_t Switch = 0x01BD87;
  constexpr uint24_t Background = 0x01BEBB;
  constexpr uint24_t Menu = 0x01D6BD;
  constexpr uint24_t Block_12 = 0x01F00F;
  constexpr uint24_t Block_13 = 0x01F329;
  constexpr uint24_t Block_21 = 0x01F74B;
  constexpr uint24_t Block_31 = 0x01FB3D;
  constexpr uint24_t Key = 0x02010F;
  constexpr uint24_t Cursor = 0x020501;
  constexpr uint24_t Levels = 0x020713;
  constexpr uint24_t Levels_Cursor = 0x022C95;
  constexpr uint24_t Levels_HUD = 0x022E17;
  constexpr uint24_t Levels_Status = 0x027D99;
  constexpr uint24_t Levels_Number = 0x027F1E;
  constexpr uint24_t Levels_NumberOfMoves = 0x028448;
  constexpr uint24_t Levels_NumberOfMoves_Numbers = 0x02855E;
  constexpr uint24_t Numbers_5x3_1D_MB = 0x0285F6;
  constexpr uint24_t Numbers_5x3_2D_MB = 0x0286AC;
}

