#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfd9b;
constexpr uint24_t FX_DATA_BYTES = 152586;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x018810;
  constexpr uint24_t Sound_Volume_Grey = 0x01B812;
  constexpr uint24_t Sound_Volume_White = 0x01C054;
  constexpr uint24_t Sound_Checkbox = 0x01C896;
  constexpr uint24_t Title = 0x01C8A4;
  constexpr uint24_t HUD_Top = 0x020C26;
  constexpr uint24_t HUD_Bottom = 0x021B40;
  constexpr uint24_t FreeTheKey = 0x0231E6;
  constexpr uint24_t Background = 0x023DE8;
  constexpr uint24_t Block_12 = 0x0249EA;
  constexpr uint24_t Block_13 = 0x024B30;
  constexpr uint24_t Block_21 = 0x024CE2;
  constexpr uint24_t Block_31 = 0x024EAC;
  constexpr uint24_t Key = 0x025166;
  constexpr uint24_t Cursor = 0x025330;
}

